services:
  - postgresql
addons:
  hosts:
    - init.overtime-api.example.com
    - example.com
env:
  global:
    - CC_TEST_REPORTER_ID=49732dc4446084d4e0b922707e35d014aa9972ed2e37c016d7af5693a8e72ae2
language: node_js
node_js:
  - '11.10.1'
before_script:
  - npm install sequelize-cli -g
  - psql -c 'create database vla_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
